project: Bees
environment: Dev
business_entity_service: https://api-gateway-dev.ab-inbev.cn/business-entity-service/
bees_user_service: https://api-gateway-dev.ab-inbev.cn/
products_service: https://api-gateway-dev.ab-inbev.cn/products-service/
MYSQL_CONNECT:
  HOST: rm-uf6t3m8yo40d5b905go.mysql.rds.aliyuncs.com
  PASSWD: zhaoyawei@123
  PORT: 3306
  USER: un_zhaoyawei
token_method: Static
bees_console_token_abi: f4a1093c-ef3d-4887-a4c1-6aaa3bebebe9
bees_console_token_t1: 1c03c590-c471-4b97-b789-5ddeb658c18f
bees_console_token_t2: be1ad4eb-843f-43b1-bc2f-17f1f36f6482
bees_m1_token: 79da3a81-25b5-430d-8054-96f47b867e2e
